# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("skills", "0002_auto_20170113_0321")]

    operations = [
        migrations.AddField(
            model_name="skillwithstate",
            name="online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="skillwithstate",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="with_states",
                to="skills.Skill",
            ),
        ),
        migrations.AlterField(
            model_name="skillwithstate",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"", b"Select State"),
                    (b"Abia", b"Abia"),
                    (b"Abuja", b"Abuja"),
                    (b"Adamawa", b"Adamawa"),
                    (b"Akwa Ibom", b"Akwa Ibom"),
                    (b"Anambra", b"Anambra"),
                    (b"Bayelsa", b"Bayelsa"),
                    (b"Bauchi", b"Bauchi"),
                    (b"Benue", b"Benue"),
                    (b"Borno", b"Borno"),
                    (b"Cross River", b"Cross River"),
                    (b"Delta", b"Delta"),
                    (b"Edo", b"Edo"),
                    (b"Ebonyi", b"Ebonyi"),
                    (b"Ekiti", b"Ekiti"),
                    (b"Enugu", b"Enugu"),
                    (b"Gombe", b"Gombe"),
                    (b"Imo", b"Imo"),
                    (b"Jigawa", b"Jigawa"),
                    (b"Kaduna", b"Kaduna"),
                    (b"Kano", b"Kano"),
                    (b"Katsina", b"Katsina"),
                    (b"Kebbi", b"Kebbi"),
                    (b"Kogi", b"Kogi"),
                    (b"Kwara", b"Kwara"),
                    (b"Lagos", b"Lagos"),
                    (b"Nassawara", b"Nassawara"),
                    (b"Niger", b"Niger"),
                    (b"Ogun", b"Ogun"),
                    (b"Ondo", b"Ondo"),
                    (b"Osun", b"Osun"),
                    (b"Oyo", b"Oyo"),
                    (b"Plateau", b"Plateau"),
                    (b"Rivers", b"Rivers"),
                    (b"Sokoto", b"Sokoto"),
                    (b"Taraba", b"Taraba"),
                    (b"Yobe", b"Yobe"),
                    (b"Zamfara", b"Zamfara"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
