# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        # ("external", "0014_auto_20180322_1138"),
        ("skills", "0003_auto_20170119_1649"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("priority",), "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="subcategory", options={"verbose_name_plural": "SubCategories"}
        ),
        migrations.AddField(
            model_name="tutorskill",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external.Agent",
            ),
        ),
        migrations.AddField(
            model_name="tutorskill",
            name="image_denied_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="skill",
            name="heading",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="skill",
            name="market_category",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "School"), (2, "Exams"), (3, "Languages"), (4, "Skills")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="short_name",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="skill",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="subheading",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="skill",
            name="testimonial",
            field=models.TextField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="skillwithstate",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select State"),
                    ("Abia", "Abia"),
                    ("Abuja", "Abuja"),
                    ("Adamawa", "Adamawa"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Anambra", "Anambra"),
                    ("Bayelsa", "Bayelsa"),
                    ("Bauchi", "Bauchi"),
                    ("Benue", "Benue"),
                    ("Borno", "Borno"),
                    ("Cross River", "Cross River"),
                    ("Delta", "Delta"),
                    ("Edo", "Edo"),
                    ("Ebonyi", "Ebonyi"),
                    ("Ekiti", "Ekiti"),
                    ("Enugu", "Enugu"),
                    ("Gombe", "Gombe"),
                    ("Imo", "Imo"),
                    ("Jigawa", "Jigawa"),
                    ("Kaduna", "Kaduna"),
                    ("Kano", "Kano"),
                    ("Katsina", "Katsina"),
                    ("Kebbi", "Kebbi"),
                    ("Kogi", "Kogi"),
                    ("Kwara", "Kwara"),
                    ("Lagos", "Lagos"),
                    ("Nassawara", "Nassawara"),
                    ("Niger", "Niger"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                    ("Osun", "Osun"),
                    ("Oyo", "Oyo"),
                    ("Plateau", "Plateau"),
                    ("Rivers", "Rivers"),
                    ("Sokoto", "Sokoto"),
                    ("Taraba", "Taraba"),
                    ("Yobe", "Yobe"),
                    ("Zamfara", "Zamfara"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Academic Subjects", "Academic Subjects"),
                    ("Exams & Languages", "Exams & Languages"),
                    ("Non Academic Subjects", "Non Academic Subjects"),
                ],
                max_length=70,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="days_per_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1day per week"),
                    (2, "2days per week"),
                    (3, "3days per week"),
                    (4, "4days per week"),
                    (5, "5days per week"),
                    (6, "6days per week"),
                    (7, "7days per week"),
                ],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="discount",
            field=models.IntegerField(
                choices=[
                    (0, "0%"),
                    (10, "10%"),
                    (15, "15%"),
                    (20, "20%"),
                    (25, "25%"),
                    (30, "30%"),
                    (35, "35%"),
                    (40, "40%"),
                    (45, "45%"),
                    (50, "50%"),
                ],
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(50),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="hours_per_day",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1hr per day"),
                    (2, "2hrs per day"),
                    (3, "3hrs per day"),
                    (4, "4hrs per day"),
                    (5, "5hrs per day"),
                ],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="max_student",
            field=models.IntegerField(
                choices=[
                    (1, "1 student "),
                    (2, "2 students "),
                    (3, "3 students "),
                    (4, "4 students "),
                    (5, "5 students "),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=70, populate_from="heading"
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="status",
            field=models.IntegerField(
                choices=[
                    (2, "Active"),
                    (3, "Suspended"),
                    (1, "Pending Approval"),
                    (4, "Denied"),
                    (5, "Require Modification"),
                    (6, "Freee Subject"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="tutorskill",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
