# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("skills", "0004_auto_20180322_1138")]

    operations = [
        migrations.AddField(
            model_name="tutorskill",
            name="remark",
            field=models.TextField(blank=True, null=True),
        )
    ]
