# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('skills', '0004_auto_20180322_1138'),
    # ]
    dependencies = [
        ('skills', '0005_tutorskill_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsitting',
            name='tutor_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
