# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-08 14:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0005_quizsitting_tutor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorskill",
            name="other_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default={}
            ),
        ),
    ]
