# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-10-13 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0006_auto_20211008_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectexhibition",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
