# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=70)),
                ("score", models.IntegerField()),
                ("one_time", models.BooleanField(default=False)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=b"condition"
                    ),
                ),
            ],
        )
    ]
