# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  gitlabhub: 'Gitlab Tuteria'
  imageName: 'registry.gitlab.com/tuteria/tuteria'
  shortName: "tuteria/tuteria"


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/compose/django/Dockerfile'
        tags: |
          $(tag)
        buildContext: '$(Build.SourcesDirectory)'
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(gitlabhub)
        repository: $(shortName)
        command: push
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy App
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'SSH Connection'
        runOptions: 'commands'
        commands: 'ls -la'
        readyTimeout: '20000'
      
