# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 07:08
from __future__ import unicode_literals

import config.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillReview",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                (
                    "review_type",
                    models.IntegerField(
                        choices=[
                            (1, b"From user to tutor"),
                            (2, b"From tutor to user"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="bookings.Booking",
                    ),
                ),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="skills.TutorSkill",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "abstract": False,
                "get_latest_by": "modified",
            },
        ),
        migrations.CreateModel(
            name="TutorMeeting",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        db_index=True, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, b"issued"),
                            (2, b"payed"),
                            (3, b"accepted"),
                            (4, b"rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("led_to_booking", models.BooleanField(default=False)),
                (
                    "time_to_call",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"", b"Best Time to Call"),
                            (b"morining", b"9am - 11am"),
                            (b"afternoon", b"1pm - 3pm"),
                            (b"evening", b"5pm - 7pm"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("made_payment", models.BooleanField(default=False)),
                ("viewed_by_tutor", models.BooleanField(default=False)),
                ("met_with_client", models.BooleanField(default=False)),
                (
                    "meeting_outcome",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("admin_request", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ts",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.TutorSkill",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(config.utils.BookingDetailMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="tutormeeting", unique_together=set([("client", "tutor")])
        ),
    ]
