# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-23 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('connect_tutor', '0003_auto_20210516_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorjobresponse',
            name='response_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
