# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-10 13:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('connect_tutor', '0004_auto_20210823_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpool',
            name='other_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        
    ]
