# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 07:08
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("email_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "abstract": False,
                "get_latest_by": "modified",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ref_instance",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=b"user",
                    ),
                ),
                ("used_credit", models.BooleanField(default=False)),
                ("first_class", models.BooleanField(default=False)),
                ("first_booking", models.BooleanField(default=False)),
                (
                    "ref_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("offline_code", models.CharField(blank=True, max_length=5, null=True)),
                ("offline", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("downloaded_form", models.BooleanField(default=False)),
                ("flyer_date", models.DateTimeField(blank=True, null=True)),
                (
                    "no_of_months",
                    models.IntegerField(
                        choices=[(1, b"3 months"), (100, b"Unlimited months")],
                        default=1,
                    ),
                ),
                ("agreed_percent", models.IntegerField(default=0)),
                ("percent_discount", models.IntegerField(default=0)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("15000"), max_digits=16
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referrals.Referral",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "abstract": False,
                "get_latest_by": "modified",
            },
        ),
        migrations.AddField(
            model_name="emailinvite",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
