# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("referrals", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="no_of_months",
            field=models.IntegerField(
                choices=[(1, "3 months"), (100, "Unlimited months")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="offline_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="ref_instance",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
