# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 06:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "low"), (2, "medium"), (3, "high")], default=1
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select State"),
                            ("Kaduna", "Kaduna"),
                            ("Bauchi", "Bauchi"),
                            ("Kogi", "Kogi"),
                            ("Anambra", "Anambra"),
                            ("Imo", "Imo"),
                            ("Oyo", "Oyo"),
                            ("Plateau", "Plateau"),
                            ("Akwa Ibom", "Akwa Ibom"),
                            ("Cross River", "Cross River"),
                            ("Katsina", "Katsina"),
                            ("Gombe", "Gombe"),
                            ("Adamawa", "Adamawa"),
                            ("Zamfara", "Zamfara"),
                            ("Abuja", "Abuja"),
                            ("Ogun", "Ogun"),
                            ("Sokoto", "Sokoto"),
                            ("Delta", "Delta"),
                            ("Taraba", "Taraba"),
                            ("Benue", "Benue"),
                            ("Jigawa", "Jigawa"),
                            ("Yobe", "Yobe"),
                            ("Borno", "Borno"),
                            ("Kebbi", "Kebbi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Ekiti", "Ekiti"),
                            ("Ebonyi", "Ebonyi"),
                            ("Enugu", "Enugu"),
                            ("Kano", "Kano"),
                            ("Osun", "Osun"),
                            ("Ondo", "Ondo"),
                            ("Edo", "Edo"),
                            ("Rivers", "Rivers"),
                            ("Lagos", "Lagos"),
                            ("Kwara", "Kwara"),
                            ("Nassawara", "Nassawara"),
                            ("Niger", "Niger"),
                            ("Abia", "Abia"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                (
                    "areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("prices", models.ManyToManyField(to="pricings.Pricing")),
            ],
        ),
    ]
