# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pricings", "0003_auto_20161003_0628")]

    operations = [
        migrations.AddField(
            model_name="region",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1500, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="category",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="region_factor",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Plan 1"), (2, "Plan 2"), (3, "Plan 3")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select State"),
                    ("Ondo", "Ondo"),
                    ("Edo", "Edo"),
                    ("Bayelsa", "Bayelsa"),
                    ("Ekiti", "Ekiti"),
                    ("Kaduna", "Kaduna"),
                    ("Benue", "Benue"),
                    ("Anambra", "Anambra"),
                    ("Abuja", "Abuja"),
                    ("Lagos", "Lagos"),
                    ("Adamawa", "Adamawa"),
                    ("Abia", "Abia"),
                    ("Kogi", "Kogi"),
                    ("Ogun", "Ogun"),
                    ("Zamfara", "Zamfara"),
                    ("Osun", "Osun"),
                    ("Oyo", "Oyo"),
                    ("Rivers", "Rivers"),
                    ("Plateau", "Plateau"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Bauchi", "Bauchi"),
                    ("Borno", "Borno"),
                    ("Cross River", "Cross River"),
                    ("Kwara", "Kwara"),
                    ("Imo", "Imo"),
                    ("Kebbi", "Kebbi"),
                    ("Enugu", "Enugu"),
                    ("Katsina", "Katsina"),
                    ("Yobe", "Yobe"),
                    ("Jigawa", "Jigawa"),
                    ("Niger", "Niger"),
                    ("Ebonyi", "Ebonyi"),
                    ("Sokoto", "Sokoto"),
                    ("Kano", "Kano"),
                    ("Gombe", "Gombe"),
                    ("Nassawara", "Nassawara"),
                    ("Taraba", "Taraba"),
                    ("Delta", "Delta"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
