# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pricings", "0005_auto_20180112_2058")]

    operations = [
        migrations.RemoveField(model_name="region", name="prices"),
        migrations.AlterField(
            model_name="region",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select State"),
                    ("Kogi", "Kogi"),
                    ("Adamawa", "Adamawa"),
                    ("Abia", "Abia"),
                    ("Kano", "Kano"),
                    ("Kebbi", "Kebbi"),
                    ("Niger", "Niger"),
                    ("Rivers", "Rivers"),
                    ("Borno", "Borno"),
                    ("Gombe", "Gombe"),
                    ("Plateau", "Plateau"),
                    ("Lagos", "Lagos"),
                    ("Ondo", "Ondo"),
                    ("Bauchi", "Bauchi"),
                    ("Oyo", "Oyo"),
                    ("Benue", "Benue"),
                    ("Jigawa", "Jigawa"),
                    ("Cross River", "Cross River"),
                    ("Enugu", "Enugu"),
                    ("Delta", "Delta"),
                    ("Bayelsa", "Bayelsa"),
                    ("Abuja", "Abuja"),
                    ("Zamfara", "Zamfara"),
                    ("Ogun", "Ogun"),
                    ("Ebonyi", "Ebonyi"),
                    ("Taraba", "Taraba"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Anambra", "Anambra"),
                    ("Kaduna", "Kaduna"),
                    ("Imo", "Imo"),
                    ("Kwara", "Kwara"),
                    ("Edo", "Edo"),
                    ("Ekiti", "Ekiti"),
                    ("Osun", "Osun"),
                    ("Nassawara", "Nassawara"),
                    ("Katsina", "Katsina"),
                    ("Sokoto", "Sokoto"),
                    ("Yobe", "Yobe"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
