# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-09-20 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210920_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='data_dump',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
