# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-01-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_data_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=3000, verbose_name='Question'),
        ),
    ]
