# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-01-10 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_delete_newtutorapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('registration.guarantor',),
        ),
        migrations.CreateModel(
            name='TutorApplicantTrack',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='NewTutorApplicant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('tutor_management.tutorapplicanttrack',),
        ),
    ]
