# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 07:09
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import wallet.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestToWithdraw",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "charge",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("order", models.CharField(db_index=True, max_length=12, null=True)),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "abstract": False,
                "get_latest_by": "modified",
            },
        ),
        migrations.CreateModel(
            name="UserPayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_type",
                    models.IntegerField(choices=[(1, b"Bank Transfer")], default=1),
                ),
                ("account_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"", b"Select Bank"),
                            (b"Citibank", b"Citibank"),
                            (b"Access Bank", b"Access Bank"),
                            (b"Diamond Bank", b"Diamond Bank"),
                            (b"Ecobank Nigeria", b"Ecobank Nigeria"),
                            (b"Enterprise Bank", b"Enterprise Bank"),
                            (b"Fidelity Bank Nigeria", b"Fidelity Bank Nigeria"),
                            (b"First Bank of Nigeria", b"First Bank of Nigeria"),
                            (b"First City Monument Bank", b"First City Monument Bank"),
                            (b"First Inland Bank", b"First Inland Bank"),
                            (b"Guaranty Trust Bank", b"Guaranty Trust Bank"),
                            (b"Heritage Bank", b"Heritage Bank"),
                            (b"Keystone Bank Limited", b"Keystone Bank Limited"),
                            (b"Mainstreet Bank", b"Mainstreet Bank"),
                            (b"Skye Bank", b"Skye Bank"),
                            (b"Stanbic IBTC Bank", b"Stanbic IBTC Bank"),
                            (b"Standard Chartered Bank", b"Standard Chartered Bank"),
                            (b"Sterling Bank", b"Sterling Bank"),
                            (b"Union Bank of Nigeria", b"Union Bank of Nigeria"),
                            (b"United Bank for Africa", b"United Bank for Africa"),
                            (b"Unity Bank", b"Unity Bank"),
                            (b"Wema Bank", b"Wema Bank"),
                            (b"Zenith Bank", b"Zenith Bank"),
                        ],
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "amount_available",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "amount_in_session",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "credit_in_session",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "previous_available_balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[(b"user", b"user"), (b"admin", b"admin")],
                        default=b"user",
                        max_length=10,
                    ),
                ),
                (
                    "authorization_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("auto_withdraw", models.BooleanField(default=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "abstract": False,
                "get_latest_by": "modified",
            },
            bases=(wallet.mixins.WalletMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, b"DEPOSIT"),
                            (2, b"TUTOR_HIRE"),
                            (3, b"WITHDRAWAL"),
                            (4, b"TUTOR EARNING"),
                            (5, b"SERVICE_CHARGE"),
                            (6, b"REFUND"),
                            (7, b"CANCELLATION_PENALTY"),
                            (8, b"TUTERIA_EARNING"),
                            (9, b"REFERRAL_CREDIT"),
                            (10, b"ACCOUNT_LOAD_CREDIT"),
                            (11, b"BONUS_CREDIT"),
                            (12, b"BACKGROUND_CHECK"),
                            (13, b"WITHDRAWAL_COMPLETED"),
                            (14, b"REQUEST_TUTOR"),
                            (16, b"REFERRAL_NEW_BOOKING"),
                            (15, b"REFERRAL_BOOKING_MADE"),
                            (17, b"REFERRAL_PAYMENT"),
                            (18, b"PROCESSING_FEE"),
                        ]
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            (b"income", b"income"),
                            (b"expenditure", b"expenditure"),
                        ],
                        default=b"income",
                        max_length=15,
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "extra_message",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="bookings.Booking",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.Wallet",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "abstract": False,
                "get_latest_by": "modified",
            },
        ),
        migrations.AddField(
            model_name="requesttowithdraw",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.UserPayout",
            ),
        ),
        migrations.AddField(
            model_name="requesttowithdraw",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BookingNotPaid",
            fields=[],
            options={"proxy": True},
            bases=("wallet.wallettransaction",),
        ),
        migrations.AlterUniqueTogether(
            name="userpayout", unique_together=set([("user", "payout_type")])
        ),
    ]
