# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="remark",
            field=models.TextField(blank=True, null=True),
        )
    ]
