# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0002_wallettransaction_remark")]

    operations = [
        migrations.AddField(
            model_name="requesttowithdraw",
            name="transfer_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userpayout",
            name="recipient_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userpayout",
            name="bank",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"", b"Select Bank"),
                    (b"Citibank", b"Citibank"),
                    (b"Access Bank", b"Access Bank"),
                    (b"Diamond Bank", b"Diamond Bank"),
                    (b"Ecobank Nigeria", b"Ecobank Nigeria"),
                    (b"Enterprise Bank", b"Enterprise Bank"),
                    (b"Fidelity Bank Nigeria", b"Fidelity Bank Nigeria"),
                    (b"First Bank of Nigeria", b"First Bank of Nigeria"),
                    (b"First City Monument Bank", b"First City Monument Bank"),
                    (b"First Inland Bank", b"First Inland Bank"),
                    (b"Guaranty Trust Bank", b"Guaranty Trust Bank"),
                    (b"Heritage Bank", b"Heritage Bank"),
                    (b"Keystone Bank Limited", b"Keystone Bank Limited"),
                    (b"Mainstreet Bank", b"Mainstreet Bank"),
                    (b"Skye Bank", b"Skye Bank"),
                    (b"Stanbic IBTC Bank", b"Stanbic IBTC Bank"),
                    (b"Standard Chartered Bank", b"Standard Chartered Bank"),
                    (b"Sterling Bank", b"Sterling Bank"),
                    (b"Union Bank of Nigeria", b"Union Bank of Nigeria"),
                    (b"United Bank for Africa", b"United Bank for Africa"),
                    (b"Unity Bank", b"Unity Bank"),
                    (b"Wema Bank", b"Wema Bank"),
                    (b"Zenith Bank", b"Zenith Bank"),
                    (b"Jaiz Bank", b"Jaiz Bank"),
                    (b"Suntrust Bank", b"Suntrust Bank"),
                    (b"Providus Bank", b"Providus Bank"),
                    (b"Parallex Bank", b"Parallex Bank"),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
