# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-05-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("external", "0018_auto_20210424_1441"),
        ("wallet", "0003_auto_20170419_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="request_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_transactions",
                to="external.BaseRequestTutor",
            ),
        ),
    ]
