# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-02-08 08:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('', 'Select'), ('B.Sc.', 'B.Sc.'), ('B.A.', 'B.A.'), ('B.Ed.', 'B.Ed.'), ('B.Eng.', 'B.Eng.'), ('B.Tech.', 'B.Tech.'), ('Diploma', 'Diploma'), ('MBBS', 'MBBS'), ('HND', 'HND'), ('OND', 'OND'), ('M.Sc.', 'M.Sc.'), ('LL.B', 'LL.B'), ('MBA', 'MBA'), ('PhD', 'PhD'), ('N.C.E', 'N.C.E'), ('S.S.C.E', 'S.S.C.E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='role',
            field=models.CharField(max_length=125, verbose_name='Role'),
        ),
    ]
