# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-01 14:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
        ('registration', '0002_auto_20210208_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='organization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
