SUBJECTS = [
    [
        "General Mathematics",
        "Basic Mathematics",
        "Algebra",
        "Arithmetic",
        "Geometry",
        "Trigonometry",
        "Quantitative Reasoning",
    ],
    [
        "Basic Sciences",
        "Biology",
        "Agricultural Science",
        "Life Sciences",
        "Chemistry",
        "Organic Chemistry",
        "Inorganic Chemistry",
        "Biochemistry",
        "Geography",
        "Genetics",
    ],
    [
        "English Language",
        "English Grammar",
        "Literature in English",
        "Spellings",
        "Reading Comprehension",
        "Vocabulary Building",
        "Verbal Reasoning",
        "Linguistics",
        "Public Speaking",
        "English Poetry",
        "Study Skills",
        "Letter Writing",
        "Essay Writing",
        "Spoken English",
        "Proofreading & Editing",
        "Handwriting Improvement",
        "Creative Writing",
    ],
    [
        "Economics",
        "Commerce",
        "Principles of Accounting",
        "Government",
        "Civic Education",
        "Business Studies",
        "Social Studies",
        "Home Economics",
        "Food & Nutrition",
        "Christian Religious Studies",
    ],
    [
        "Basic Computing",
        "Information Technology (ICT)",
        "Basic Technology",
        "Desktop Publishing",
        "Typing Skills",
        "Microsoft Outlook",
        "Microsoft Access",
        "Microsoft PowerPoint",
        "Microsoft Excel",
        "Microsoft Word",
    ],
    [
        "Piano",
        "Drums",
        "Music Theory",
        "Guitar",
        "Violin",
        "Music History",
        "Flute",
        "Clarinet",
    ],
    [
        "CORELDRAW",
        "Graphic Design",
        "Autodesk AutoCAD",
        "Adobe Photoshop",
        "Photo Editing",
        "Video Editing",
        "Photography",
        "AutoDesk Maya",
        "Video Animation",
    ],
    ["French Horn", "Trumpet", "Saxophone", "Trombone"],
    [
        "Singing",
        "Voice Training",
        "Ear Training",
        "Rapping",
        "Audition Preparation",
        "Conducting",
    ],
    [
        "Personal Finance",
        "Business Management",
        "Financial Analysis",
        "Business Administration",
        "Writing Business Plan",
        "Proposal Writing",
    ],
    [
        "Technical Drawing",
        "Drawing",
        "Fine Art",
        "Architecture",
        "Building Drawing",
        "Creative Arts",
        "Environmental Management",
    ],
    [
        "Microbiology",
        "Zoology",
        "Botany",
        "Anatomy",
        "Physiology",
        "Geology",
        "Obstetrics & Gynaecology",
    ],
    [
        "Calculus",
        "Further Mathematics",
        "Statistics",
        "Numerical Methods",
        "Differential Equations",
        "Regression & Correlation",
        "Discrete Mathematics",
        "Probability",
        "Data Analysis",
        "Physics",
        "Logic",
        "MATLAB",
        "Econometrics",
        "SPSS",
    ],
    [
        "Phonics",
        "Letters & Numbers",
        "Shapes & Body Parts",
        "Moral & Health Habits",
        "Fine Art & Nature",
        "Phonetics",
        "Elementary English",
        "Elementary Mathematics",
        "General Nursery",
    ],
    ["Chess", "Scrabble"],
    [
        "ACCA",
        "ICAN",
        "Management Accounting",
        "ACIB",
        "OCP",
        "ISMN",
        "NIPR",
        "CIPMN",
        "CITN",
    ],
    [
        "CCNA",
        "Computer Networking",
        "Computer Science",
        "Computer Repair",
        "Phone Repairs",
    ],
    [
        "Ballroom Dance",
        "Choreography",
        "Traditional Dance",
        "Ballet",
        "Yoga",
        "Film Acting",
    ],
    [
        "Political Science",
        "African History",
        "World History",
        "History",
        "Nigerian History",
        "Company Law",
        "Sociology",
        "Philosophy",
        "Law",
    ],
    ["IELTS", "TOEFL", "SAT Reading", "SAT Writing", "GMAT", "GRE", "SAT Math"],
    ["Yoruba Language"],
    ["Igbo Language"],
    ["Ibibio Language", "Annang Language"],
    ["Hausa Language"],
    ["Spanish Language", "French Language", "German Language", "Chinese Language"],
    ["Arabic Language", "Islamic Religious Studies"],
    ["Facial Beauty", "Make up", "Hair Weaving", "Cosmetology", "Hair Styling"],
    [
        "Cloth Customization",
        "Fashion Designing",
        "Ankara Craft",
        "Sewing & Tailoring",
        "Needle Work",
        "Gele Tying",
        "Decoration",
        "Face Treatment",
        "Fashion Drawing",
        "Wedding Planning",
        "Flat Stomach",
        "Bead Making",
        "Wire Works",
        "Bag Making",
        "Jewelry Design",
    ],
    [
        "Customer Experience",
        "Etiquette",
        "Career Counselling",
        "Contract Management",
        "Procument & Inventory",
    ],
    [
        "Afang Soup",
        "Edikaikong Soup",
        "Igbo Soups",
        "Calabar Soups",
        "Ofada Soup",
        "Okro Soup",
        "Bitter Leaf Soup",
        "Egusi Soup",
    ],
    [
        "Electrical Engineering",
        "Chemical Engineering",
        "Software Engineering",
        "Thermodynamics",
        "Electronics",
        "Mechanical Engineering",
        "Civil Engineering",
        "Artificial Intelligence",
        "Mechatronics",
        "Engineering",
    ],
    [
        "Cake Making",
        "Small Chops",
        "Assorted Meals",
        "Confectionaries",
        "General Cooking",
        "Continental Dishes",
        "Health Coaching",
        "Nutritious Eating",
        "Reproductive Health",
    ],
    [
        "PMP",
        "NIM",
        "PMI",
        "ORACLE Certification",
        "Negotiation Skills",
        "Business Etiquette",
        "Business Development",
        "SAS Business Analytics and Intelligence Software",
    ],
    [
        "Digital Marketing",
        "Social Media Marketing",
        "Blog Management",
        "Book Publishing",
    ],
    [
        "Java Programming",
        "PHP Programming",
        "Mobile App Development",
        "C# Programming",
        "SQL",
        "Data Structures",
        "Python Programming",
        "Linux OS",
        "C++ Programming",
        "C Programming",
        "Web Development",
        "Web Design",
    ],
    [
        "Swimming",
        "Football Coaching",
        "Martial Arts",
        "Physical Education",
        "Fitness & Exercise",
        "Body Building",
        "Basketball Coaching",
        "Self Defence",
        "Kung Fu",
        "Gymnastics",
        "Taekuondo",
        "Volleyball",
        "Lawn Tennis",
    ],
    ["Hard of Hearing", "Dyslexia", "ADD/ADHD", "Special Needs", "Autism"],
    ["Drilling and Completions", "Oilfield Maths", "Offshore Training"],
]


def convert_to_lower_case():
    return [[x.lower() for x in y] for y in SUBJECTS]


def get_related_subjects(subject:str):
    for x in convert_to_lower_case():
        # split subject basedon certain delimeters like -
        pairs = [j.strip() for j in subject.split("-")]
        uu = [u for u in pairs if u.lower() in x]
        if uu:
            return x
        if subject.lower() in x:
            return x
    return [subject]


def found_s(subject):
    for x in convert_to_lower_case():
        if subject.lower() in x:
            return True
    return False
