# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-21 15:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('exam', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('course_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='last name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'UNPAID'), (2, 'PAID')], default=1)),
                ('payment_medium', models.IntegerField(choices=[(0, 'None'), (1, 'Online'), (2, 'Bank Transfer')], default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('with_others', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('where_you_heard', models.CharField(blank=True, default='', max_length=200)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_referred', to='courses.CourseUser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Courses Request',
                'verbose_name_plural': 'Video Courses Requests',
            },
        ),
    ]
