# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="_description_rendered"),
        migrations.RemoveField(
            model_name="userprofile", name="description_markup_type"
        ),
        migrations.AlterField(
            model_name="userprofile", name="description", field=models.TextField()
        ),
    ]
