# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 06:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20160820_0657")]

    operations = [
        migrations.CreateModel(
            name="Constituency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            (b"", b"Select State"),
                            (b"Abia", b"Abia"),
                            (b"Abuja", b"Abuja"),
                            (b"Adamawa", b"Adamawa"),
                            (b"Akwa Ibom", b"Akwa Ibom"),
                            (b"Anambra", b"Anambra"),
                            (b"Bayelsa", b"Bayelsa"),
                            (b"Bauchi", b"Bauchi"),
                            (b"Benue", b"Benue"),
                            (b"Borno", b"Borno"),
                            (b"Cross River", b"Cross River"),
                            (b"Delta", b"Delta"),
                            (b"Edo", b"Edo"),
                            (b"Ebonyi", b"Ebonyi"),
                            (b"Ekiti", b"Ekiti"),
                            (b"Enugu", b"Enugu"),
                            (b"Gombe", b"Gombe"),
                            (b"Imo", b"Imo"),
                            (b"Jigawa", b"Jigawa"),
                            (b"Kaduna", b"Kaduna"),
                            (b"Kano", b"Kano"),
                            (b"Katsina", b"Katsina"),
                            (b"Kebbi", b"Kebbi"),
                            (b"Kogi", b"Kogi"),
                            (b"Kwara", b"Kwara"),
                            (b"Lagos", b"Lagos"),
                            (b"Nassawara", b"Nassawara"),
                            (b"Niger", b"Niger"),
                            (b"Ogun", b"Ogun"),
                            (b"Ondo", b"Ondo"),
                            (b"Osun", b"Osun"),
                            (b"Oyo", b"Oyo"),
                            (b"Plateau", b"Plateau"),
                            (b"Rivers", b"Rivers"),
                            (b"Sokoto", b"Sokoto"),
                            (b"Taraba", b"Taraba"),
                            (b"Yobe", b"Yobe"),
                            (b"Zamfara", b"Zamfara"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "related_with",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.Constituency",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="users.Constituency",
            ),
        ),
    ]
