# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20160928_0752")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teach_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="constituency",
            name="related_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Constituency",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="users.Constituency",
            ),
        ),
    ]
