# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20161130_2114")]

    operations = [
        migrations.CreateModel(
            name="ApprovingTutor",
            fields=[],
            options={"proxy": True},
            bases=("users.user",),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Constituency",
            ),
        ),
    ]
