# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20161214_1420")]

    operations = [
        migrations.CreateModel(
            name="CustomerManagement",
            fields=[],
            options={"proxy": True},
            bases=("users.user",),
        ),
        migrations.AddField(
            model_name="user",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
