# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_auto_20170125_0720")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="applied_for_prime",
            field=models.BooleanField(default=False),
        )
    ]
