# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 14:33
from __future__ import unicode_literals

import autoslug.fields
import cloudinary.models
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0008_userprofile_applied_for_prime")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_dump",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constituency",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select State"),
                    ("Abia", "Abia"),
                    ("Abuja", "Abuja"),
                    ("Adamawa", "Adamawa"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Anambra", "Anambra"),
                    ("Bayelsa", "Bayelsa"),
                    ("Bauchi", "Bauchi"),
                    ("Benue", "Benue"),
                    ("Borno", "Borno"),
                    ("Cross River", "Cross River"),
                    ("Delta", "Delta"),
                    ("Edo", "Edo"),
                    ("Ebonyi", "Ebonyi"),
                    ("Ekiti", "Ekiti"),
                    ("Enugu", "Enugu"),
                    ("Gombe", "Gombe"),
                    ("Imo", "Imo"),
                    ("Jigawa", "Jigawa"),
                    ("Kaduna", "Kaduna"),
                    ("Kano", "Kano"),
                    ("Katsina", "Katsina"),
                    ("Kebbi", "Kebbi"),
                    ("Kogi", "Kogi"),
                    ("Kwara", "Kwara"),
                    ("Lagos", "Lagos"),
                    ("Nassawara", "Nassawara"),
                    ("Niger", "Niger"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                    ("Osun", "Osun"),
                    ("Oyo", "Oyo"),
                    ("Plateau", "Plateau"),
                    ("Rivers", "Rivers"),
                    ("Sokoto", "Sokoto"),
                    ("Taraba", "Taraba"),
                    ("Yobe", "Yobe"),
                    ("Zamfara", "Zamfara"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="addr_type",
            field=models.IntegerField(
                choices=[
                    (1, "User Address"),
                    (2, "Tutor Address"),
                    (3, "Neutral Address"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select State"),
                    ("Abia", "Abia"),
                    ("Abuja", "Abuja"),
                    ("Adamawa", "Adamawa"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Anambra", "Anambra"),
                    ("Bayelsa", "Bayelsa"),
                    ("Bauchi", "Bauchi"),
                    ("Benue", "Benue"),
                    ("Borno", "Borno"),
                    ("Cross River", "Cross River"),
                    ("Delta", "Delta"),
                    ("Edo", "Edo"),
                    ("Ebonyi", "Ebonyi"),
                    ("Ekiti", "Ekiti"),
                    ("Enugu", "Enugu"),
                    ("Gombe", "Gombe"),
                    ("Imo", "Imo"),
                    ("Jigawa", "Jigawa"),
                    ("Kaduna", "Kaduna"),
                    ("Kano", "Kano"),
                    ("Katsina", "Katsina"),
                    ("Kebbi", "Kebbi"),
                    ("Kogi", "Kogi"),
                    ("Kwara", "Kwara"),
                    ("Lagos", "Lagos"),
                    ("Nassawara", "Nassawara"),
                    ("Niger", "Niger"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                    ("Osun", "Osun"),
                    ("Oyo", "Oyo"),
                    ("Plateau", "Plateau"),
                    ("Rivers", "Rivers"),
                    ("Sokoto", "Sokoto"),
                    ("Taraba", "Taraba"),
                    ("Yobe", "Yobe"),
                    ("Zamfara", "Zamfara"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, populate_from="sluger", sep="", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="useridentification",
            name="doc_type",
            field=models.CharField(
                choices=[("identity", "identity")], default="identity", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="useridentification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="application_status",
            field=models.IntegerField(
                choices=[
                    (0, "NOT APPLIED"),
                    (1, "BEGAN APPLICATION"),
                    (2, "APPLICATION COMPLETED PENDING REVIEW"),
                    (3, "VERIFIED"),
                    (4, "DENIED"),
                    (6, "MARKED AS DENIED"),
                    (5, "MARKED AS VERIFIED"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="blog_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="booking_prep",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("", "Select option"),
                    (0, "Always ready"),
                    (1, "At least 1 day"),
                    (2, "At least 2 days"),
                    (3, "At least 3 days"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cancellation",
            field=models.CharField(
                choices=[
                    ("Flexible", "Flexible"),
                    ("Moderate", "Moderate"),
                    ("Strict", "Strict"),
                ],
                default="Flexible",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="curriculum_used",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("1", "Nigerian"), ("2", "British"), ("3", "American")],
                    max_length=30,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="custom_header",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="days",
            field=models.IntegerField(
                default=0, null=True, verbose_name="max_no_of_days"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="dob"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                db_index=True,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="handle",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hours",
            field=models.IntegerField(
                default=0, null=True, verbose_name="max_no_of_hours"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, default="", max_length=100, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="interview_slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Best Time to Call"),
                    ("morining", "9am - 11am"),
                    ("afternoon", "1pm - 3pm"),
                    ("evening", "5pm - 7pm"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "new tutor"),
                    (1, "influencer"),
                    (2, "role model"),
                    (3, "super tutor"),
                    (4, "leader"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="registration_level",
            field=models.IntegerField(
                choices=[
                    (0, "Not Began"),
                    (1, "Credentials"),
                    (2, "Preference"),
                    (3, "Interview"),
                    (4, "Interview22"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="response_time",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("", "Select"),
                    (30, "in 30 minutes"),
                    (60, "in 1 hour"),
                    (120, "in 2 hours"),
                    (180, "in 3 hours"),
                    (300, "in 5 hours"),
                ],
                default=0,
                verbose_name="Response Time",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutor_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutoring_address",
            field=models.CharField(
                choices=[
                    ("user", "Client's Location"),
                    ("tutor", "Tutor's Location"),
                    ("neutral", "Anywhere convenient"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutoring_distance",
            field=models.CharField(
                choices=[
                    ("near", "at most 5km (~ 30mins drive )"),
                    ("not far", "at most 10km (~ 1hrs drive )"),
                    ("quite far", "at most 15km (~ 1.5hrs drive )"),
                    ("far", "at most 20km (~ 2hrs drive )"),
                    ("very far", "greater than 20km (the whole state)"),
                ],
                default="near",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="years_of_teaching",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("", "Just starting out"),
                    (2, "Less than 2 years"),
                    (5, "Between 3 to 5 years"),
                    (10, "Between 6 to 10 years"),
                    (50, "More than 10 years"),
                ],
                null=True,
            ),
        ),
    ]
