# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("external", "0014_auto_20180322_1138"),
        ("users", "0009_auto_20180109_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external.Agent",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tutor_skill_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="display name"
            ),
        ),
    ]
