# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-01-10 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220108_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTutorApplicant',
        ),
    ]
