# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-05-05 12:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_newtutorapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='vicinity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
