# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bookings", "0002_booking_remark")]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_level",
            field=models.IntegerField(
                choices=[(0, b"65"), (1, b"75"), (2, b"75"), (3, b"80"), (4, b"85")],
                default=1,
            ),
        )
    ]
