# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bookings", "0003_booking_booking_level")]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="dealId",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
