# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bookings", "0004_auto_20171110_0730")]

    operations = [
        migrations.CreateModel(
            name="BookingSummary",
            fields=[],
            options={
                "verbose_name": "Booking Summary",
                "verbose_name_plural": "Booking Summary",
                "proxy": True,
                "indexes": [],
            },
            bases=("bookings.bookingsession",),
        ),
        migrations.CreateModel(
            name="FollowUpBooking",
            fields=[],
            options={"proxy": True, "indexes": []},
            bases=("bookings.booking",),
        ),
        migrations.AddField(
            model_name="booking",
            name="squashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="squashed_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_level",
            field=models.IntegerField(
                choices=[(0, "65%"), (1, "70%"), (2, "75%"), (3, "80%"), (4, "85%")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.IntegerField(
                choices=[(1, "hourly"), (2, "monthly")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "initialized"),
                    (1, "scheduled"),
                    (2, "pending"),
                    (3, "completed"),
                    (4, "cancelled"),
                    (6, "bank_transfer"),
                    (7, "delivered"),
                    (8, "premature"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="skills.TutorSkill",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="t_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookingsession",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Reason"),
                    ("change_location", "Changing Location"),
                    ("no_need_for_lesson", "Don't need lesson anymore"),
                    ("dislike_tutor", "Didn't like the tutor"),
                    ("family_inconvenience", "Family Inconvenience (e.g Illness)"),
                    ("tutor_no_showing_up", "Tutor didn't show up"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookingsession",
            name="issue",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Issue"),
                    ("more_hours", "I taught more than the booked hours"),
                    ("client_not_cooperative", "Client was not cooperative"),
                    ("late_lesson", "Lesson did not start on time"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bookingsession",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "not started"),
                    (2, "started"),
                    (3, "completed"),
                    (5, "cancelled"),
                ],
                default=1,
            ),
        ),
    ]
