# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-03 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20171221_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookings',
            field=models.ManyToManyField(related_name='_booking_bookings_+', to='bookings.Booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='group_bookings',
            field=models.ManyToManyField(related_name='sessions', to='bookings.Booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_level',
            field=models.IntegerField(choices=[(50, '50%'), (55, '55%'), (60, '60%'), (0, '65%'), (1, '70%'), (2, '75%'), (3, '80%'), (4, '85%')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
