# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('external', '0016_auto_20190618_1547'),
        ('bookings', '0006_auto_20190103_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external.Agent'),
        ),
      
    ]
