# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-05-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20190618_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transport_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='tuteria_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        )
    ]
