# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-05-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20210523_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='witholding_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
